### ISSUE TITLE
What do you think about the graph I created?

### ISSUE THREAD

**Issue by alkestis-s** [bburtin/brkt-cli#2]
Hi @bobveznat @bburtin ,  

my team and I are currently working on automated generation of architecture diagrams for CloudFormation and serverless projects. Your project is particularly interesting as it represents a good real-world use case. 

The tool we are working on generated [the following diagram](https://bit.ly/2T0LEES) for your repo. I am happy to get your feedback about it. It would be very helpful for our product development. 

Does the diagram match the architecture you have in mind? 

Cheers,
Al

**Comment by bburtin** [comment]
Thanks for your interest.  The company that developed brkt-cli has gone out of business.  There will be no more development on this project.
